apiVersion: v2
name: minimalist-web-notepad
description: WORKSHOP - The ultimate notepad for DaplaLab.
icon: https://cdn-icons-png.flaticon.com/512/686/686112.png
keywords:
  - Notepad
sources:
# A chart can be either an 'application' or a 'library' chart.
  - https://github.com/statisticsnorway/workshop-dapla-lab-helm-charts
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.2

dependencies:
  - name: library-chart
    version: 1.0.1
    repository: https://statisticsnorway.github.io/dapla-lab-helm-charts-services
