apiVersion: v1
kind: Secret
metadata:
  name: redash-postgres
type: Opaque
data:
  connectionString: {{ printf "postgresql://%s:%s@%s:5432/%s" .Values.global.postgresql.auth.username .Values.global.postgresql.auth.password .Values.postgresql.fullnameOverride .Values.global.postgresql.auth.database| b64enc | quote }}